nohup python3 -u main.py \
    -root "../data/" \
    -dt "wmt" \
    -minfreq 2 \
    -maxlen 30 \
    -stp 20 \
    -bs 32 \
    -pee 5 \
    -cuda \
    -emptymem \
    -hid 600 \
    -emd 300 \
    -enhl 3 \
    -dnhl 1 \
    -mth "general" \
    -drop 0.0 \
    -lnorm \
    -thres 5 \
    -lr 0.001 \
    -declr 5.0 \
    -wdk 0.00001 \
    -save \
    -savebest \
    -svpe "./saved_models/wmt.enc" \
    -svpd "./saved_models/wmt.dec" > ../trainlog/nmt_wmt.log &
