nohup python3 -u main.py \
    -root "../data/" \
    -dt "wmt" \
    -minfreq 1 \
    -stp 20 \
    -bs 16 \
    -pee 10 \
    -cuda \
    -emptymem \
    -hid 600 \
    -emd 300 \
    -nhl 1 \
    -mth "general" \
    -drop 0.1 \
    -thres 5 \
    -lr 0.001 \
    -declr 5.0 \
    -wdk 0.00001 \
    -save \
    -savebest \
    -svpe "./saved_models/wmt.enc" \
    -svpd "./saved_models/wmt.dec" > ../trainlog/nmt_wmt.log &