nohup python3 -u main.py \
    -root "../data/" \
    -dt "iwslt" \
    -minfreq 2 \
    -stp 20 \
    -maxlen 50 \
    -bs 16 \
    -pee 1000 \
    -cuda \
    -emptymem \
    -hid 600 \
    -emd 300 \
    -nhl 3 \
    -mth "general" \
    -drop 0.1 \
    -thres 5 \
    -lr 0.001 \
    -declr 5.0 \
    -save \
    -savebest \
    -svpe "./saved_models/iswlt2.enc" \
    -svpd "./saved_models/iswlt2.dec" \
    -load \
    -ldpe "./saved_models/iswlt.dec" \
    -ldpd "./saved_models/iswlt.enc" > ../trainlog/nmt2.log &
