nohup python3 -u main.py \
    -root "../data/" \
    -dt "iwslt" \
    -minfreq 2 \
    -stp 30 \
    -maxlen 30 \
    -bs 50 \
    -pee 5 \
    -cuda \
    -emptymem \
    -hid 512 \
    -emd 256 \
    -enhl 3 \
    -dnhl 1 \
    -mth "general" \
    -drop 0.2 \
    -lnorm \
    -thres 5 \
    -lr 0.001 \
    -tf \
    -declr 5.0 \
    -wdk 0.00001 \
    -optim "adam" \
    -save \
    -savebest \
    -svpe "./saved_models/iswlt.enc" \
    -svpd "./saved_models/iswlt.dec" > ../trainlog/nmt.log &
